- name: "Install python-related packages debian/ubuntu"
  apt: pkg={{ item }} state=latest
  with_items:
    - python
    - python-dev
    - python-setuptools

- name: "Install pip"
  easy_install: name=pip

- name: "Install virtualenv"
  pip: name=virtualenv

- name: "Install pyzmq"
  pip: name={{ item }}
  with_items:
    - pyzmq
    - pyopenssl
    - ndg-httpsclient
    - pyasn1
