- name: "Update apt package cache"
  apt: update_cache=yes

- name: "Install common packages debian/ubuntu"
  apt: pkg={{ item }} state=latest
  with_items:
    - build-essential
    - git
    - supervisor
    - libxml2-dev
    - cmake
    - pkg-config
